services:

    backend-staging:
      image: sychin0606/backend:latest
      platform: linux/amd64
      container_name: backend-con-staging
      ports:
        - "8000:8000" 
      env_file:
        - ../../env/.env.stag_machine
      environment:
        ENV_FILE: /app/env/.env.stag_machine
      networks:
        - mlops-network-staging
        
    frontend-staging:
      image: sychin0606/frontend:latest
      platform: linux/amd64
      container_name: frontend-con-staging
      ports:
        - "8501:8501"
      env_file:
         - ../../env/.env.stag_machine
      environment:
        MODEL_SERVER_IP: http://backend-con-staging:8000
        ENV_FILE: /app/env/.env.stag_machine
      networks:
        - mlops-network-staging
      depends_on:
        - backend-staging

networks:
  mlops-network-staging:
    driver: bridge

# Usage:
# docker compose -f infra/docker/docker-compose.staging.yml up
