services:

    backend:
      image: sychin0606/backend:latest
      platform: linux/amd64
      container_name: backend-con
      ports:
        - "8000:8000"
      env_file:
        - ../../env/.env.dev_machine
      networks:
        - mlops-network

    frontend:
      #build:
      #    context: ../../
      #    dockerfile: infra/docker/Dockerfile.frontend
      image: sychin0606/frontend:latest
      platform: linux/amd64
      container_name: frontend-con
      ports:
        - "8501:8501"
      environment:
        MODEL_SERVER_IP: http://backend-con:8000
      networks:
        - mlops-network
      depends_on:
        - backend

networks:
  mlops-network:
    driver: bridge

# docker compose -f infra/docker/docker-compose.dev.yml up

