services:

    api-staging:
      image: sychin0606/fraud-api:latest
      platform: linux/amd64
      container_name: api-con-staging
      ports:
        - "8080:8000" 
      env_file:
        - ../env/.env.stag_machine
      networks:
        - mlops-network-staging
    frontend-staging:
      image: sychin0606/frontend:latest
      platform: linux/amd64
      container_name: frontend-con-staging
      ports:
        - "8501:8501"
      environment:
        MODEL_SERVER_IP: http://api-con-staging:8000
      networks:
        -  mlops-network-staging
      depends_on:
        - api-staging

networks:
  mlops-network-staging:
    driver: bridge

# Usage:
# docker compose -f infra/docker/docker-compose.staging.yml up
