services:
    backend-prod:
      image: sychin0606/backend:latest
      platform: linux/amd64
      container_name: backend-con-prod
      ports:
        - "8000:8000"  
      env_file:
        - ../../env/.env.prod_machine
      environment:
        ENV_FILE: /app/env/.env.prod_machine
      networks:
        - mlops-network-prod
  
    frontend-prod:
      image: sychin0606/frontend:latest
      platform: linux/amd64
      container_name: frontend-con
      ports:
        - "8501:8501"
      env_file:
         - ../../env/.env.prod_machine
      environment:
        MODEL_SERVER_IP: http://backend-con-prod:8000
        ENV_FILE: /app/env/.env.prod_machine
      networks:
        - mlops-network-prod
      depends_on:
        - backend-prod
networks:
  mlops-network-prod:
    driver: bridge

# Usage:
# docker compose -f infra/docker/docker-compose.prod.yml up
