data_ingestion:
  raw_data_path:  data/raw/
  train_data_path: data/processed/train.csv
  test_data_path: data/processed/test.csv
  test_size: 0.3
  random_state: 42

data_transformation:
  processed_train_data_path: data/processed/processed_train.csv
  processed_test_data_path: data/processed/processed_test.csv
  preprocessor_ob_file_path: outputs/artifacts/preprocessor.pkl

model_trainer:
  trained_model_file_path: outputs/models/model.pkl
  metrics_file_path: outputs/metrics/metrics.json
  processed_train_data_path: data/processed/processed_train.csv
  processed_test_data_path: data/processed/processed_test.csv

predict_pipeline:
  model_path: outputs/models/model.pkl
  preprocessor_path: outputs/artifacts/preprocessor.pkl