services:
    
    mlflow:
      build: 
        context: .
        dockerfile: Dockerfile.mlflow
      container_name: mlflow-server
      ports:
        - "5050:5050"   
      env_file:
        - .env

    train:
      build: 
        context: .
        dockerfile: Dockerfile.mlflow
      container_name: mlops-train
      depends_on:
        - mlflow
      #volumes:
      #  - .:/app 
      working_dir: /app