FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .
COPY src src
COPY data data
COPY .dvc .dvc
COPY dvc.lock .
COPY dvc.yaml .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose MLflow port
EXPOSE 5050

# Run MLflow using environment variables
CMD ["dvc", "repro"]

# docker build -t mlops-train -f Dockerfile.train .
