FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git gcc

COPY requirements.txt .
COPY src src
COPY data data

RUN pip install --upgrade pip
RUN pip install --no-cache-dir "dvc[s3]"
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5050

CMD ["sh", "-c", "python -m src.pipeline.run_pipeline"]
# docker build -t mlops-train -f docker/Dockerfile.train .
# docker run --rm -it --env-file .env mlops-train
