services:
    
    mlflow:
      build: 
        context: ..
        dockerfile: docker/Dockerfile.mlflow
      container_name: mlflow-server
      ports:
        - "5050:5050"   
      env_file:
        - ../.env


# docker compose -f docker/docker-compose.yml up

