services:
    mlflow-staging:
      image: sychin0606/mlflow-server:latest
      container_name: mlflow-server-staging
      ports:
        - "5051:5050"   # External port 5051 → Internal port 5050
      env_file:
        - ../.env.staging
      networks:
        - mlops-network-staging

    api-staging:
      image: sychin0606/fraud-api:latest
      platform: linux/amd64
      container_name: api-con-staging
      ports:
        - "8081:8000"  # External port 8081 → Internal port 8000
      environment:
        MLFLOW_TRACKING_URI: http://mlflow-staging:5050
      env_file:
        - ../.env.staging
      networks:
        - mlops-network-staging
      depends_on:
        - mlflow-staging

networks:
  mlops-network-staging:
    driver: bridge

# Usage:
# docker compose -f docker/docker-compose.staging.yml up
