services:
    
    api:
      build: 
        context: ..
        dockerfile: docker/Dockerfile.api
      container_name: api-con
      ports:
        - "5060:5050"
      environment:
        - MLFLOW_TRACKING_URI: http://mlflow-server:5050 
        - REGISTERED_MODEL_NAME: fraud-detection-model
      env_file:
        - ../.env


  # docker compose -f docker/docker-compose-api.yml up
