FROM python:3.11-slim

WORKDIR /app

COPY /frontend ./frontend/

RUN pip install -r frontend/requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "frontend/fraud_detection_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]


# docker build --platform linux/amd64 -t sychin0606/frontend:latest -f docker/Dockerfile.frontend .
# docker push sychin0606/frontend:latest