services:
    
    mlflow:
      build: 
        context: .
        dockerfile: Dockerfile.mlflow
      container_name: mlflow-server
      ports:
        - "5050:5050"   
      env_file:
        - .env

    api:
      build: .
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:5051
        - REGISTERED_MODEL_NAME=fraud-detection-model
      ports:
        - "5050:5050"
      depends_on:
        - mlflow