FROM python:3.11-slim

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY src/ ./src/ 

EXPOSE 5050

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "5060"]


# docker run -p 5050:5050 fraud-api
# docker run --env-file .env -p 5060:5050 fraud-api /bin/bash
