services:
    
    mlflow:
      build: 
        context: ..
        dockerfile: docker/Dockerfile.mlflow
      container_name: mlflow-server
      ports:
        - "5000:5050"   
      env_file:
        - ../.env
      networks:
        - mlops-network

    train:
      build: 
        context: ..
        dockerfile: docker/Dockerfile.train
      container_name: mlops-train
      depends_on:
        - mlflow
      working_dir: /app
      env_file:
        - ../.env
      networks:
        - mlops-network
      environment:
        MLFLOW_TRACKING_URI: http://mlflow-server:5050 

networks:
  mlops-network:
    driver: bridge
    
# docker compose -f docker/docker-compose.yml up

