services:
    mlflow:
      image: sychin0606/mlflow-server:latest
      container_name: mlflow-server
      ports:
        - "5050:5050"   
      env_file:
        - ../.env
      networks:
        - mlops-network

    api:
      image: sychin0606/fraud-api:latest
      platform: linux/amd64
      container_name: api-con
      ports:
        - "8080:8000"
      environment:
        MLFLOW_TRACKING_URI: http://mlflow-server:5050
      env_file:
        - ../.env
      networks:
        - mlops-network
      depends_on:
        - mlflow

networks:
  mlops-network:
    driver: bridge

# docker compose -f docker/docker-compose.yml up

