# not used
services:
  postgres:
    image: postgres:15
    container_name: postgres-ci
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflowdb
    ports:
      - "5433:5432"  
    networks:
      - ci-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflowdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: mlflow-ci
    ports:
      - "5051:5051"
    env_file:
        - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge


# docker compose -f docker/docker-compose.ci.yml up
