name: CI - dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    # --- Define MLflow service ---
    services:
      mlflow:
        image: sychin0606/ci:latest
        ports:
          - 5051:5051
        options: >-
          --platform linux/amd64
          --health-cmd "curl --fail http://localhost:5051 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
     
      - name: Load environment variables
        run: |
          cat .env.dev >> $GITHUB_ENV

      - name: Install packages
        run: pip install -r requirements/dev.txt

      - name: Run quality checks
        run: make check

      - name: Run pipeline
        run: make run-pipeline

      # --- Step 4: Run tests ---
      #- name: Run pytest
      #  run:  make test