name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          make install

      #- name: Lint with pyLint
      #  run: |
      #    make lint

      - name: Test with pytest
        run: |
          make test

      - name: Format code
        run: |
          make format

      - name: Data processing and Training pipeline
        run: 
          make run-pipeline

      - name: Start Streamlit app
        run: 
          make app
