name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          make install

      - name: Create .env file
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
          echo "MODEL_SERVER_IP=${{ secrets.MODEL_SERVER_IP }}" >> .env
          echo "MODEL_ALIAS=champion" >> .env
          echo "REGISTERED_MODEL_NAME=fraud-detection-model" >> .env
          
      #- name: Lint with pyLint
      #  run: |
      #    make lint

      - name: Test with pytest
        run: |
          make test

      - name: Format code
        run: |
          make format

      - name: Data processing and Training pipeline
        run: 
          make run-pipeline

      - name: Start Streamlit app
        run: 
          make app
