name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          make install

      - name: Start MLflow server (local, for CI)
        run: |
          mlflow server --host 127.0.0.1 --port 8081
          sleep 5

      - name: Data processing and Training pipeline
        env:
          MLFLOW_TRACKING_URI: http://localhost:8081
          RUN_NAME: sample_run
          DATASET_NAME: creditcard.csv
          ARTIFACT_PATH: logreg_model
          ALGORITHM_TYPE: logistic-regression
          REGISTERED_MODEL_NAME: fraud-detection-model
        run: 
          make run-pipeline

      #- name: Lint with pyLint
      #  run: |
      #    make lint

  # - name: Test with pytest
  #   env:
  #     MLFLOW_TRACKING_URI: http://localhost:8081
  #     MODEL_SERVER_IP: localhost
  #     REGISTERED_MODEL_NAME: fraud-detection-model
  #     MODEL_ALIAS: champion
  #   run: |
  #     make test

      - name: Format code
        run: |
          make format

      - name: Data processing and Training pipeline
        run: 
          make run-pipeline

  # - name: Start Streamlit app
  #   run: 
  #     make app
