name: CI - dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install packages
        run: make install

      # --- Step 1: Run linting/formatting/flake all in one ---
      - name: Run quality checks
        run: make check

      # --- Step 2: Start lightweight services ---
      - name: Start lightweight MLflow service
        run: |
          docker compose -f docker-compose.ci.yml up -d
          sleep 15  # wait for MLflow to be ready

      # --- Step 3: Run training pipeline ---
      - name: Run data processing & training pipeline
        env:
          path: .env.dev
        run: make run-pipeline

      # --- Step 4: Run tests ---
      - name: Run pytest
        env:
          path: .env.dev
        run: make format #make test
