name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Create .env file
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
          echo "MODEL_SERVER_IP=${{ secrets.MODEL_SERVER_IP }}" >> .env
          echo "MODEL_ALIAS=champion" >> .env
          echo "REGISTERED_MODEL_NAME=fraud-detection-model" >> .env

      - name: Start services
        run: docker compose -f docker/docker-compose.yml up -d mlflow

      - name: Show mlflow logs
        run: docker compose -f docker/docker-compose.yml logs mlflow
  
      - name: Wait for services
        run: sleep 10
        
      - name: Check API and MLflow server container
        run: |
          docker ps 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with Pytest
        #env:
        #  MODEL_SERVER_IP: ${{ secrets.MODEL_SERVER_IP }}
        #  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
         # MODEL_ALIAS: champion
          #REGISTERED_MODEL_NAME: fraud-detection-model
        run: |
          pytest tests/
          
      - name: Build and push API image
        run: |
          docker build -t sychin0606/fraud-api:latest -f docker/Dockerfile.api .
          docker push sychin0606/fraud-api:latest

